# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Desktop/opencv_projects/plane_detection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Desktop/opencv_projects/plane_detection

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/opencv_projects/plane_detection/CMakeFiles /home/user/Desktop/opencv_projects/plane_detection/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/opencv_projects/plane_detection/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PMDDetector

# Build rule for target.
PMDDetector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PMDDetector
.PHONY : PMDDetector

# fast build rule for target.
PMDDetector/fast:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/build
.PHONY : PMDDetector/fast

Detector.o: Detector.cpp.o

.PHONY : Detector.o

# target to build an object file
Detector.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/Detector.cpp.o
.PHONY : Detector.cpp.o

Detector.i: Detector.cpp.i

.PHONY : Detector.i

# target to preprocess a source file
Detector.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/Detector.cpp.i
.PHONY : Detector.cpp.i

Detector.s: Detector.cpp.s

.PHONY : Detector.s

# target to generate assembly for a file
Detector.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/Detector.cpp.s
.PHONY : Detector.cpp.s

FrameObject.o: FrameObject.cpp.o

.PHONY : FrameObject.o

# target to build an object file
FrameObject.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/FrameObject.cpp.o
.PHONY : FrameObject.cpp.o

FrameObject.i: FrameObject.cpp.i

.PHONY : FrameObject.i

# target to preprocess a source file
FrameObject.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/FrameObject.cpp.i
.PHONY : FrameObject.cpp.i

FrameObject.s: FrameObject.cpp.s

.PHONY : FrameObject.s

# target to generate assembly for a file
FrameObject.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/FrameObject.cpp.s
.PHONY : FrameObject.cpp.s

FramePlane.o: FramePlane.cpp.o

.PHONY : FramePlane.o

# target to build an object file
FramePlane.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/FramePlane.cpp.o
.PHONY : FramePlane.cpp.o

FramePlane.i: FramePlane.cpp.i

.PHONY : FramePlane.i

# target to preprocess a source file
FramePlane.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/FramePlane.cpp.i
.PHONY : FramePlane.cpp.i

FramePlane.s: FramePlane.cpp.s

.PHONY : FramePlane.s

# target to generate assembly for a file
FramePlane.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/FramePlane.cpp.s
.PHONY : FramePlane.cpp.s

PlaneDetector.o: PlaneDetector.cpp.o

.PHONY : PlaneDetector.o

# target to build an object file
PlaneDetector.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/PlaneDetector.cpp.o
.PHONY : PlaneDetector.cpp.o

PlaneDetector.i: PlaneDetector.cpp.i

.PHONY : PlaneDetector.i

# target to preprocess a source file
PlaneDetector.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/PlaneDetector.cpp.i
.PHONY : PlaneDetector.cpp.i

PlaneDetector.s: PlaneDetector.cpp.s

.PHONY : PlaneDetector.s

# target to generate assembly for a file
PlaneDetector.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/PlaneDetector.cpp.s
.PHONY : PlaneDetector.cpp.s

Util.o: Util.cpp.o

.PHONY : Util.o

# target to build an object file
Util.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/Util.cpp.o
.PHONY : Util.cpp.o

Util.i: Util.cpp.i

.PHONY : Util.i

# target to preprocess a source file
Util.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/Util.cpp.i
.PHONY : Util.cpp.i

Util.s: Util.cpp.s

.PHONY : Util.s

# target to generate assembly for a file
Util.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/Util.cpp.s
.PHONY : Util.cpp.s

mainPMD.o: mainPMD.cpp.o

.PHONY : mainPMD.o

# target to build an object file
mainPMD.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/mainPMD.cpp.o
.PHONY : mainPMD.cpp.o

mainPMD.i: mainPMD.cpp.i

.PHONY : mainPMD.i

# target to preprocess a source file
mainPMD.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/mainPMD.cpp.i
.PHONY : mainPMD.cpp.i

mainPMD.s: mainPMD.cpp.s

.PHONY : mainPMD.s

# target to generate assembly for a file
mainPMD.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/mainPMD.cpp.s
.PHONY : mainPMD.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... PMDDetector"
	@echo "... rebuild_cache"
	@echo "... Detector.o"
	@echo "... Detector.i"
	@echo "... Detector.s"
	@echo "... FrameObject.o"
	@echo "... FrameObject.i"
	@echo "... FrameObject.s"
	@echo "... FramePlane.o"
	@echo "... FramePlane.i"
	@echo "... FramePlane.s"
	@echo "... PlaneDetector.o"
	@echo "... PlaneDetector.i"
	@echo "... PlaneDetector.s"
	@echo "... Util.o"
	@echo "... Util.i"
	@echo "... Util.s"
	@echo "... mainPMD.o"
	@echo "... mainPMD.i"
	@echo "... mainPMD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

