# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Desktop/opencv_projects/PMD_detector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Desktop/opencv_projects/PMD_detector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/opencv_projects/PMD_detector/CMakeFiles /home/user/Desktop/opencv_projects/PMD_detector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/opencv_projects/PMD_detector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PMDDetector

# Build rule for target.
PMDDetector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PMDDetector
.PHONY : PMDDetector

# fast build rule for target.
PMDDetector/fast:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/build
.PHONY : PMDDetector/fast

src/Detector.o: src/Detector.cpp.o

.PHONY : src/Detector.o

# target to build an object file
src/Detector.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Detector.cpp.o
.PHONY : src/Detector.cpp.o

src/Detector.i: src/Detector.cpp.i

.PHONY : src/Detector.i

# target to preprocess a source file
src/Detector.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Detector.cpp.i
.PHONY : src/Detector.cpp.i

src/Detector.s: src/Detector.cpp.s

.PHONY : src/Detector.s

# target to generate assembly for a file
src/Detector.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Detector.cpp.s
.PHONY : src/Detector.cpp.s

src/FrameObject.o: src/FrameObject.cpp.o

.PHONY : src/FrameObject.o

# target to build an object file
src/FrameObject.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/FrameObject.cpp.o
.PHONY : src/FrameObject.cpp.o

src/FrameObject.i: src/FrameObject.cpp.i

.PHONY : src/FrameObject.i

# target to preprocess a source file
src/FrameObject.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/FrameObject.cpp.i
.PHONY : src/FrameObject.cpp.i

src/FrameObject.s: src/FrameObject.cpp.s

.PHONY : src/FrameObject.s

# target to generate assembly for a file
src/FrameObject.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/FrameObject.cpp.s
.PHONY : src/FrameObject.cpp.s

src/FramePlane.o: src/FramePlane.cpp.o

.PHONY : src/FramePlane.o

# target to build an object file
src/FramePlane.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/FramePlane.cpp.o
.PHONY : src/FramePlane.cpp.o

src/FramePlane.i: src/FramePlane.cpp.i

.PHONY : src/FramePlane.i

# target to preprocess a source file
src/FramePlane.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/FramePlane.cpp.i
.PHONY : src/FramePlane.cpp.i

src/FramePlane.s: src/FramePlane.cpp.s

.PHONY : src/FramePlane.s

# target to generate assembly for a file
src/FramePlane.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/FramePlane.cpp.s
.PHONY : src/FramePlane.cpp.s

src/Hand.o: src/Hand.cpp.o

.PHONY : src/Hand.o

# target to build an object file
src/Hand.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Hand.cpp.o
.PHONY : src/Hand.cpp.o

src/Hand.i: src/Hand.cpp.i

.PHONY : src/Hand.i

# target to preprocess a source file
src/Hand.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Hand.cpp.i
.PHONY : src/Hand.cpp.i

src/Hand.s: src/Hand.cpp.s

.PHONY : src/Hand.s

# target to generate assembly for a file
src/Hand.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Hand.cpp.s
.PHONY : src/Hand.cpp.s

src/HandClassifier.o: src/HandClassifier.cpp.o

.PHONY : src/HandClassifier.o

# target to build an object file
src/HandClassifier.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/HandClassifier.cpp.o
.PHONY : src/HandClassifier.cpp.o

src/HandClassifier.i: src/HandClassifier.cpp.i

.PHONY : src/HandClassifier.i

# target to preprocess a source file
src/HandClassifier.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/HandClassifier.cpp.i
.PHONY : src/HandClassifier.cpp.i

src/HandClassifier.s: src/HandClassifier.cpp.s

.PHONY : src/HandClassifier.s

# target to generate assembly for a file
src/HandClassifier.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/HandClassifier.cpp.s
.PHONY : src/HandClassifier.cpp.s

src/HandDetector.o: src/HandDetector.cpp.o

.PHONY : src/HandDetector.o

# target to build an object file
src/HandDetector.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/HandDetector.cpp.o
.PHONY : src/HandDetector.cpp.o

src/HandDetector.i: src/HandDetector.cpp.i

.PHONY : src/HandDetector.i

# target to preprocess a source file
src/HandDetector.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/HandDetector.cpp.i
.PHONY : src/HandDetector.cpp.i

src/HandDetector.s: src/HandDetector.cpp.s

.PHONY : src/HandDetector.s

# target to generate assembly for a file
src/HandDetector.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/HandDetector.cpp.s
.PHONY : src/HandDetector.cpp.s

src/PlaneDetector.o: src/PlaneDetector.cpp.o

.PHONY : src/PlaneDetector.o

# target to build an object file
src/PlaneDetector.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/PlaneDetector.cpp.o
.PHONY : src/PlaneDetector.cpp.o

src/PlaneDetector.i: src/PlaneDetector.cpp.i

.PHONY : src/PlaneDetector.i

# target to preprocess a source file
src/PlaneDetector.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/PlaneDetector.cpp.i
.PHONY : src/PlaneDetector.cpp.i

src/PlaneDetector.s: src/PlaneDetector.cpp.s

.PHONY : src/PlaneDetector.s

# target to generate assembly for a file
src/PlaneDetector.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/PlaneDetector.cpp.s
.PHONY : src/PlaneDetector.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/Visualizer.o: src/Visualizer.cpp.o

.PHONY : src/Visualizer.o

# target to build an object file
src/Visualizer.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Visualizer.cpp.o
.PHONY : src/Visualizer.cpp.o

src/Visualizer.i: src/Visualizer.cpp.i

.PHONY : src/Visualizer.i

# target to preprocess a source file
src/Visualizer.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Visualizer.cpp.i
.PHONY : src/Visualizer.cpp.i

src/Visualizer.s: src/Visualizer.cpp.s

.PHONY : src/Visualizer.s

# target to generate assembly for a file
src/Visualizer.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/Visualizer.cpp.s
.PHONY : src/Visualizer.cpp.s

src/mainPMD.o: src/mainPMD.cpp.o

.PHONY : src/mainPMD.o

# target to build an object file
src/mainPMD.cpp.o:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/mainPMD.cpp.o
.PHONY : src/mainPMD.cpp.o

src/mainPMD.i: src/mainPMD.cpp.i

.PHONY : src/mainPMD.i

# target to preprocess a source file
src/mainPMD.cpp.i:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/mainPMD.cpp.i
.PHONY : src/mainPMD.cpp.i

src/mainPMD.s: src/mainPMD.cpp.s

.PHONY : src/mainPMD.s

# target to generate assembly for a file
src/mainPMD.cpp.s:
	$(MAKE) -f CMakeFiles/PMDDetector.dir/build.make CMakeFiles/PMDDetector.dir/src/mainPMD.cpp.s
.PHONY : src/mainPMD.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... PMDDetector"
	@echo "... rebuild_cache"
	@echo "... src/Detector.o"
	@echo "... src/Detector.i"
	@echo "... src/Detector.s"
	@echo "... src/FrameObject.o"
	@echo "... src/FrameObject.i"
	@echo "... src/FrameObject.s"
	@echo "... src/FramePlane.o"
	@echo "... src/FramePlane.i"
	@echo "... src/FramePlane.s"
	@echo "... src/Hand.o"
	@echo "... src/Hand.i"
	@echo "... src/Hand.s"
	@echo "... src/HandClassifier.o"
	@echo "... src/HandClassifier.i"
	@echo "... src/HandClassifier.s"
	@echo "... src/HandDetector.o"
	@echo "... src/HandDetector.i"
	@echo "... src/HandDetector.s"
	@echo "... src/PlaneDetector.o"
	@echo "... src/PlaneDetector.i"
	@echo "... src/PlaneDetector.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/Visualizer.o"
	@echo "... src/Visualizer.i"
	@echo "... src/Visualizer.s"
	@echo "... src/mainPMD.o"
	@echo "... src/mainPMD.i"
	@echo "... src/mainPMD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

